#!/bin/sh
#
# @name Gazebo x500 lidar 3d
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_3d}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Allow arming/offboard without a GCS heartbeat for headless, scripted
# SLAM test runs (no QGroundControl attached).
param set-default NAV_DLL_ACT 0
